export const MAX_RECOMMENDED_MILESTONES = 4;
export const MIN_MILESTONES_REQUIRED = 1;
export const MIN_OBJECTIVES_REQUIRED_FOR_REQUIRED_MILESTONES = 2;
export const MAX_OBJECTIVES_REQUIRED_FOR_REQUIRED_MILESTONES = 3;
